# Generated by Django 4.1.6 on 2023-02-06 19:52

import discordlogin.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("discordlogin", "0003_alter_discorduser_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffUser",
            fields=[
                (
                    "discorduser_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="discordlogin.discorduser",
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
            bases=("discordlogin.discorduser",),
            managers=[
                ("objects", discordlogin.managers.DiscordUserOAuth2Manager()),
            ],
        ),
    ]
