# Generated by Django 4.1.6 on 2023-02-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discordlogin", "0004_staffuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="discorduser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name="StaffUser",
        ),
    ]
