# Generated by Django 4.1.6 on 2023-02-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discordlogin", "0005_discorduser_is_active_delete_staffuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="discorduser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
