# Generated by Django 4.1.5 on 2023-02-01 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_basket"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
        migrations.AlterModelOptions(
            name="productcategory",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
