# Generated by Django 4.1.5 on 2023-01-08 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={
                "ordering": ["city", "name"],
                "verbose_name": "Бригада",
                "verbose_name_plural": "Бригады",
            },
        ),
    ]
