# Generated by Django 4.1.5 on 2023-01-08 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0002_alter_team_options"),
        ("cities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Object",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Объект")),
                ("amount_people", models.IntegerField(verbose_name="Количество людей")),
                (
                    "head",
                    models.CharField(max_length=200, verbose_name="ФИО ответственного"),
                ),
                (
                    "qualification",
                    models.CharField(
                        max_length=150, verbose_name="Должность ответственного"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cities.city",
                        verbose_name="Город",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teams.team",
                        verbose_name="Бригада",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объект",
                "verbose_name_plural": "Объекты",
                "ordering": ["city", "team", "name"],
            },
        ),
    ]
