# Generated by Django 4.1.5 on 2023-01-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Город'),
        ),
    ]
